### ISSUE TITLE
plv8 error is not catchable

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deeplinks#126]
# Code
https://github.com/deep-foundation/deeplinks/blob/66e9e4f655994aaa1c630533d9afc15475990bf3/tests/sync-handlers.ts#L1241-L1268

# Error 
```
    ApolloError: Success! Handler is called

      at new ApolloError (node_modules/@apollo/client/errors/index.js:29:28)
      at node_modules/@apollo/client/core/QueryManager.js:96:47
      at both (node_modules/@apollo/client/utilities/observables/asyncMap.js:16:53)
      at node_modules/@apollo/client/utilities/observables/asyncMap.js:9:72
      at Object.then (node_modules/@apollo/client/utilities/observables/asyncMap.js:9:24)
      at Object.next (node_modules/@apollo/client/utilities/observables/asyncMap.js:17:49)
      at notifySubscription (node_modules/zen-observable/lib/Observable.js:135:18)
      at onNotify (node_modules/zen-observable/lib/Observable.js:179:3)
      at SubscriptionObserver.next (node_modules/zen-observable/lib/Observable.js:235:7)
```

# Expected 
Error is thrown from deep.insert therefore try-catch block catches it

**Comment by Konard** [comment]
![image](https://user-images.githubusercontent.com/1431904/226925731-1c61aa19-9c8f-441e-8878-27ce5a328cec.png)
![image](https://user-images.githubusercontent.com/1431904/226925753-1946d930-5662-44be-be18-8baac685dc08.png)
