### ISSUE TITLE
serial updates returns one result

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deeplinks#149]
# SerialOperations
```
[
  {
    table: 'strings',
    type: 'update',
    exp: { link_id: 2616 },
    value: { value: '111.0.0.0' }
  },
  {
    table: 'strings',
    type: 'update',
    exp: { link_id: 2618 },
    value: { value: 'Google Inc.' }
  },
]
```
# Result
```
serialResult { data: [ { id: 652, __typename: 'strings' } ] }
```

# Test Result
Tests result:
```
gitpod /workspace/dev/packages/deeplinks (main) $ npm run test -- -t "serial"
...
    serial
      ✓ insert (60 ms)
      ✓ update (68 ms)
      ✓ delete (51 ms)
      ✓ multiple inserts (56 ms)
      ✕ multiple updates (68 ms)
      ✕ multiple deletes (51 ms)
...

  ● client › serial › multiple updates

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      2
    Received:
      1
    
    Message:
      expected 1 to equal 2

      402 |         assert.equal(updateResult.error, undefined);
      403 |         assert.notEqual(updateResult.data, undefined);
    > 404 |         assert.strictEqual(updateResult.data.length, 2);
          |                ^
      405 |         const { data: [newLink] } = await deepClient.select({
      406 |           id: newLinkId
      407 |         })

      at tests/client.tsx:404:16
      at fulfilled (tests/client.tsx:5:58)

  ● client › serial › multiple deletes

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      2
    Received:
      1
    
    Message:
      expected 1 to equal 2

      439 |         assert.equal(result.error, undefined);
      440 |         assert.notEqual(result.data, undefined);
    > 441 |         assert.strictEqual(result.data.length, 2);
          |                ^
      442 |         const { data: [newLink] } = await deepClient.select(newLinkId);
      443 |         assert.equal(newLink, undefined);
      444 |       } finally {

      at tests/client.tsx:441:16
      at fulfilled (tests/client.tsx:5:58)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 140 skipped, 4 passed, 146 total
Snapshots:   0 total
Time:        3.394 s, estimated 6 s
Ran all test suites with tests matching "serial".
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @deep-foundation/deeplinks@0.0.142 test: `cross-env DEEPLINKS_HASURA_PATH=localhost:8080 DEEPLINKS_HASURA_SSL=0 DEEPLINKS_HASURA_SECRET=myadminsecretkey jest --testTimeout=50000 "-t" "serial"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @deep-foundation/deeplinks@0.0.142 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2023-04-30T05_43_25_749Z-debug.log
```

**Comment by Konard** [comment]
Are you sure that both rows are updated (changed)? What GQL is generated from this code?

**Comment by FreePhoenix888** [comment]
Tests result:
```
gitpod /workspace/dev/packages/deeplinks (main) $ npm run test -- -t "serial"
...
    serial
      ✓ insert (60 ms)
      ✓ update (68 ms)
      ✓ delete (51 ms)
      ✓ multiple inserts (56 ms)
      ✕ multiple updates (68 ms)
      ✕ multiple deletes (51 ms)
...

  ● client › serial › multiple updates

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      2
    Received:
      1
    
    Message:
      expected 1 to equal 2

      402 |         assert.equal(updateResult.error, undefined);
      403 |         assert.notEqual(updateResult.data, undefined);
    > 404 |         assert.strictEqual(updateResult.data.length, 2);
          |                ^
      405 |         const { data: [newLink] } = await deepClient.select({
      406 |           id: newLinkId
      407 |         })

      at tests/client.tsx:404:16
      at fulfilled (tests/client.tsx:5:58)

  ● client › serial › multiple deletes

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      2
    Received:
      1
    
    Message:
      expected 1 to equal 2

      439 |         assert.equal(result.error, undefined);
      440 |         assert.notEqual(result.data, undefined);
    > 441 |         assert.strictEqual(result.data.length, 2);
          |                ^
      442 |         const { data: [newLink] } = await deepClient.select(newLinkId);
      443 |         assert.equal(newLink, undefined);
      444 |       } finally {

      at tests/client.tsx:441:16
      at fulfilled (tests/client.tsx:5:58)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 140 skipped, 4 passed, 146 total
Snapshots:   0 total
Time:        3.394 s, estimated 6 s
Ran all test suites with tests matching "serial".
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @deep-foundation/deeplinks@0.0.142 test: `cross-env DEEPLINKS_HASURA_PATH=localhost:8080 DEEPLINKS_HASURA_SSL=0 DEEPLINKS_HASURA_SECRET=myadminsecretkey jest --testTimeout=50000 "-t" "serial"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @deep-foundation/deeplinks@0.0.142 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2023-04-30T05_43_25_749Z-debug.log
```

**Comment by FreePhoenix888** [comment]
> Why here we have names “exp” and “value”?

Because it is what our schema is. You can check gql to ensure that to update link you have to use exp+value
To be more clear for you as linksplatform's developer - exp is a restriction and value is a substitution :)

**Comment by FreePhoenix888** [comment]
> Are you sure that both rows are updated (changed)? What GQL is generated from this code?

I am not sure. I have to check that serial actually perform both updates and if so I have to find out why not all results are returned

**Comment by FreePhoenix888** [comment]
> Are you sure that both rows are updated (changed)? 

Yes. Both links are updated but only one result is returned
![image](https://user-images.githubusercontent.com/66206278/235338139-0128189c-9174-459e-9ab1-a6a15069490c.png)

**Comment by FreePhoenix888** [comment]
> What GQL is generated from this code?

```json
{
    "operationName": "Name",
    "variables": {
        "where0": {
            "link_id": {
                "_eq": 2354
            }
        },
        "_set0": {
            "value": "a"
        },
        "where1": {
            "link_id": {
                "_eq": 2358
            }
        },
        "_set1": {
            "value": "b"
        }
    },
    "query": "mutation Name($_set0: strings_set_input, $where0: strings_bool_exp!, $_set1: strings_set_input, $where1: strings_bool_exp!) {\n  m0: update_strings(_set: $_set0, where: $where0) {\n    returning {\n      id\n      __typename\n    }\n    __typename\n  }\n  m1: update_strings(_set: $_set1, where: $where1) {\n    returning {\n      id\n      __typename\n    }\n    __typename\n  }\n}\n"
}
```

I guess I know why this problem occurs

**Comment by FreePhoenix888** [comment]
I have logged `result` before this returning line:
https://github.com/deep-foundation/deeplinks/blob/e16471ddfe06e46b200b1c7e7a446487f10e707a/imports/client.tsx#L830

`result`'s value is
```ts
    {
      m0: { returning: [ [Object] ], __typename: 'links_mutation_response' },
      m1: { returning: [], __typename: 'links_mutation_response' }
    }
```

**Comment by FreePhoenix888** [comment]
> ```json
> {
>         "where0": {
>             "link_id": {
>                 "_eq": 2354
>             }
>         },
>         "_set0": {
>             "value": "a"
>         },
>         "where1": {
>             "link_id": {
>                 "_eq": 2358
>             }
>         },
>         "_set1": {
>             "value": "b"
>         }
>     }
> ```

If I perform this gql mutation in gql playground its returning is correct
![image](https://user-images.githubusercontent.com/66206278/235338969-324e92be-4395-4644-82ba-2432912eb5f6.png)

**Comment by FreePhoenix888** [comment]
My logs were falsy

Here is true logs:
```
  ● client › serial › multiple updates

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      2
    Received:
      1
    
    Message:
      expected 1 to equal 2

      402 |         assert.equal(updateResult.error, undefined);
      403 |         assert.notEqual(updateResult.data, undefined);
    > 404 |         assert.strictEqual(updateResult.data.length, 2);
          |                ^
      405 |         const { data: [newLink] } = await deepClient.select({
      406 |           id: newLinkId
      407 |         })

      at tests/client.tsx:404:16
      at fulfilled (tests/client.tsx:5:58)

  ● client › serial › multiple deletes

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      2
    Received:
      1
    
    Message:
      expected 1 to equal 2

      439 |         assert.equal(result.error, undefined);
      440 |         assert.notEqual(result.data, undefined);
    > 441 |         assert.strictEqual(result.data.length, 2);
          |                ^
      442 |         const { data: [newLink] } = await deepClient.select(newLinkId);
      443 |         assert.equal(newLink, undefined);
      444 |       } finally {

      at tests/client.tsx:441:16
      at fulfilled (tests/client.tsx:5:58)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 140 skipped, 4 passed, 146 total
Snapshots:   0 total
Time:        4.029 s, estimated 7 s
Ran all test suites with tests matching "serial".
  console.log
    (result)?.data

      at DeepClient.<anonymous> (imports/client.tsx:830:13)

  console.dir
    {
      m0: { returning: [ [Object] ], __typename: 'strings_mutation_response' },
      m1: { returning: [ [Object] ], __typename: 'strings_mutation_response' }
    }

      at DeepClient.<anonymous> (imports/client.tsx:831:13)

  console.log
    (result)?.data

      at DeepClient.<anonymous> (imports/client.tsx:830:13)

  console.dir
    {
      m0: { returning: [ [Object] ], __typename: 'links_mutation_response' },
      m1: { returning: [], __typename: 'links_mutation_response' }
    }

      at DeepClient.<anonymous> (imports/client.tsx:831:13)
```

**Comment by FreePhoenix888** [comment]
![image](https://user-images.githubusercontent.com/66206278/235339089-16d8de5a-073e-44e0-b0b4-debd6e93c5ad.png)
The problem is related only to deletion. Both links are returned but only one is returned

**Comment by FreePhoenix888** [comment]
```
{"operationName":"Name","variables":{"where0":{"id":{"_eq":2412}},"where1":{"id":{"_eq":2416}}},"query":"mutation Name($where0: links_bool_exp!, $where1: links_bool_exp!) {
  m0: delete_links(where: $where0) {
    returning {
      id
      __typename
    }
    __typename
  }
  m1: delete_links(where: $where1) {
    returning {
      id
      __typename
    }
    __typename
  }
}
"}
```

**Comment by FreePhoenix888** [comment]
In gql playground returning data is correct when I delete two links
![image](https://user-images.githubusercontent.com/66206278/235339248-eac74c21-9bcc-4034-a9ff-98cf35dab637.png)

**Comment by FreePhoenix888** [comment]
# Two separate delete operations
```ts
await deepClient.serial({
          operations: [
            {
              table: 'links',
              type: 'delete',
              exp: {
                id: reservedLinkIds[0]
              }
            },
            {
              table: 'links',
              type: 'delete',
              exp: {
                id: reservedLinkIds[1]
              }
            }
          ]
        })
```
```json
    {
      mutation: {
        kind: 'Document',
        definitions: [ [Object] ],
        loc: { start: 0, end: 176 }
      },
      variables: { where0: { id: [Object] }, where1: { id: [Object] } },
      mutationString: 'mutation Name ($where0: links_bool_exp!,$where1: links_bool_exp!) { m0: delete_links(where: $where0) { returning { id } }m1: delete_links(where: $where1) { returning { id } } }'
    }
```
```ts
  ● client › serial › multiple deletes

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      2
    Received:
      1
    
    Message:
      expected 1 to equal 2

      446 |         assert.equal(result.error, undefined);
      447 |         assert.notEqual(result.data, undefined);
    > 448 |         assert.strictEqual(result.data.length, 2);
          |                ^
      449 |         const { data: [newLink0] } = await deepClient.select(reservedLinkIds[0]);
      450 |         assert.equal(newLink0, undefined);
      451 |         const { data: [newLink1] } = await deepClient.select(reservedLinkIds[1]);

      at tests/client.tsx:448:16
      at fulfilled (tests/client.tsx:5:58)
```

# One delete operation with id _in
```ts
await deepClient.serial({
          operations: [
            {
              table: 'links',
              type: 'delete',
              exp: {
                id: {
                  _in: reservedLinkIds
                }
              }
            },
          ]
        });
```
```json
    {
      mutation: {
        kind: 'Document',
        definitions: [ [Object] ],
        loc: { start: 0, end: 98 }
      },
      variables: { where0: { id: [Object] } },
      mutationString: 'mutation Name ($where0: links_bool_exp!) { m0: delete_links(where: $where0) { returning { id } } }'
    }
```
```json
    {
      m0: {
        returning: [ [Object], [Object] ],
        __typename: 'links_mutation_response'
      }
    }
```

**Comment by FreePhoenix888** [comment]
I have added tests for more cases - https://github.com/deep-foundation/deeplinks/commit/c23fe13553be6879fd611aabc965564eb144a3a1
And fixed - https://github.com/deep-foundation/deeplinks/commit/c23fe13553be6879fd611aabc965564eb144a3a1
