### ISSUE TITLE
ApolloError: TextDecoder is not defined

### ISSUE THREAD

**Issue by konard** [deep-foundation/deeplinks#168]
```
  ● client › { id: { _id: ['@deep-foundation/core', 'Package'] } }

    ApolloError: TextDecoder is not defined

      at new ApolloError (node_modules/@apollo/client/errors/index.js:29:28)
      at node_modules/@apollo/client/core/QueryManager.js:657:19
      at both (node_modules/@apollo/client/utilities/observables/asyncMap.js:16:53)
      at node_modules/@apollo/client/utilities/observables/asyncMap.js:9:72
      at Object.then (node_modules/@apollo/client/utilities/observables/asyncMap.js:9:24)
      at Object.error (node_modules/@apollo/client/utilities/observables/asyncMap.js:17:49)
      at notifySubscription (node_modules/zen-observable/lib/Observable.js:140:18)
      at onNotify (node_modules/zen-observable/lib/Observable.js:179:3)
      at SubscriptionObserver.error (node_modules/zen-observable/lib/Observable.js:240:7)
      at node_modules/@apollo/client/utilities/observables/iteration.js:4:68
          at Array.forEach (<anonymous>)
      at iterateObserversSafely (node_modules/@apollo/client/utilities/observables/iteration.js:4:25)
      at Object.error (node_modules/@apollo/client/utilities/observables/Concast.js:37:21)
      at notifySubscription (node_modules/zen-observable/lib/Observable.js:140:18)
      at onNotify (node_modules/zen-observable/lib/Observable.js:179:3)
      at SubscriptionObserver.error (node_modules/zen-observable/lib/Observable.js:240:7)
      at handleError (node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.js:117:67)
      at node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.js:126:40
     
```

**Comment by Konard** [comment]
```
const { gql } = require("@apollo/client");
const { generateApolloClient } = require("@deep-foundation/hasura/client");

const apolloClient = generateApolloClient({
  path: `3006-deepfoundation-dev-d3lwbampmxc.ws-eu96b.gitpod.io/gql`,
  ssl: true,
  secret: 'myadminsecretkey',
  ws: true
});

const fn = async() => {
  const result = await apolloClient.query({ query: gql`query {links{id}}`})
  console.dir(result);
}
fn();
```

Using `node test.js` command it just works. But if run the same code inside tests, it gives `ApolloError: TextDecoder is not defined`

**Comment by Konard** [comment]
![Screenshot_20230510_131129](https://github.com/deep-foundation/deeplinks/assets/1431904/a392bdfe-9d14-4f1e-a0b1-39f9779dfad4)
