### ISSUE TITLE
deep select returns empty array of lnks in plv8 handler

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deeplinks#272]
# How to reproduce
1. Login as admin
2. Create Type contained in admin
3. Create SyncTextFile contained in admin with this value:
```typescript
({ deep, data: { newLink, triggeredByLinkId } }) => {
    throw new Error(
      JSON.stringify(
        deep.select(newLink.id)
      )
    )
}
```
4. Create Handler from plv8SupportsJs to your syncTextFile
5. Create HandleUpdate from your type to Handler
6. Insert Value from your type to String
7. Insert a link of your type
8. Update value of your link
9. See error. See that deep.select returns empty array of links

**Comment by FreePhoenix888** [comment]
Tests:
```
gitpod /workspace/dev/packages/deeplinks (main) $ npm run test -- --testNamePattern "sync handlers"

> @deep-foundation/deeplinks@0.0.322 test
> npm run package:build && cross-env DEEPLINKS_HASURA_PATH=localhost:8080 DEEPLINKS_HASURA_SSL=0 DEEPLINKS_HASURA_SECRET=myadminsecretkey DOCKER_DEEPLINKS_URL=http://localhost:3006 NODE_OPTIONS=--experimental-vm-modules jest --config jest.config.js *.js --testTimeout=50000 --testNamePattern sync handlers


> @deep-foundation/deeplinks@0.0.322 package:build
> tsc --project tsconfig.json

(node:209984) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.


 FAIL   dom  ./react.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /workspace/dev/node_modules/@react-hook/debounce/dist/module/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as React from 'react';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1505:14)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From react.test.js.


(node:209990) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:209983) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  console.log
    11

      at log (tests/sync-handlers.ts:768:19)

  console.log
    123

      at log (tests/sync-handlers.ts:770:19)

  console.log
    error Bad Request {
      internal: {
        statement: `select links__sync__handlers__deep__client(380::bigint, 'select', '{"id":1}'::jsonb, '{"table":"strings"}'::jsonb)`,
        prepared: false,
        error: {
          exec_status: 'FatalError',
          hint: null,
          message: 'select not from "links" not permitted',
          status_code: 'XX000',
          description: null
        },
        arguments: []
      },
      path: '$.args',
      error: 'query execution failed',
      code: 'postgres-error'
    }

      at Object.HasuraApi.defaultErrorHandler [as errorHandler] (../../node_modules/@deep-foundation/hasura/api.tsx:22:45)

  console.log
    error Bad Request {
      internal: {
        statement: `select links__sync__handlers__deep__client(2137::bigint, 'insert', '{"type_id":23}'::jsonb, '{}'::jsonb)`,
        prepared: false,
        error: {
          exec_status: 'FatalError',
          hint: null,
          message: 'Insert not permitted',
          status_code: 'XX000',
          description: null
        },
        arguments: []
      },
      path: '$.args',
      error: 'query execution failed',
      code: 'postgres-error'
    }

      at Object.HasuraApi.defaultErrorHandler [as errorHandler] (../../node_modules/@deep-foundation/hasura/api.tsx:22:45)

  console.log
    error Bad Request {
      internal: {
        statement: `select links__sync__handlers__deep__client(2183::bigint, 'insert', '{"type_id":23}'::jsonb, '{}'::jsonb)`,
        prepared: false,
        error: {
          exec_status: 'FatalError',
          hint: null,
          message: 'Insert not permitted',
          status_code: 'XX000',
          description: null
        },
        arguments: []
      },
      path: '$.args',
      error: 'query execution failed',
      code: 'postgres-error'
    }

      at Object.HasuraApi.defaultErrorHandler [as errorHandler] (../../node_modules/@deep-foundation/hasura/api.tsx:22:45)

  console.log
    error Bad Request {
      internal: {
        statement: `select links__sync__handlers__deep__client(2233::bigint, 'insert', '{"type_id":2263, "from_id": 2302, "to_id": 2218}'::jsonb, '{}'::jsonb)`,
        prepared: false,
        error: {
          exec_status: 'FatalError',
          hint: null,
          message: 'insert [{"id":2303,"from_id":2302,"to_id":2218,"type_id":2263}] rejected because selector_id: 2290 query_id: 2293 user_id: 2233 return false',
          status_code: 'P0001',
          description: null
        },
        arguments: []
      },
      path: '$.args',
      error: 'query execution failed',
      code: 'postgres-error'
    }

      at Object.HasuraApi.defaultErrorHandler [as errorHandler] (../../node_modules/@deep-foundation/hasura/api.tsx:22:45)

  console.log
    error Bad Request {
      internal: {
        statement: `select links__sync__handlers__deep__client(380::bigint, 'delete', '{"id":2308}'::jsonb, '{"table":"selectors"}'::jsonb)`,
        prepared: false,
        error: {
          exec_status: 'FatalError',
          hint: null,
          message: 'delete from selectors not permitted',
          status_code: 'XX000',
          description: null
        },
        arguments: []
      },
      path: '$.args',
      error: 'query execution failed',
      code: 'postgres-error'
    }

      at Object.HasuraApi.defaultErrorHandler [as errorHandler] (../../node_modules/@deep-foundation/hasura/api.tsx:22:45)

  console.log
    error Bad Request {
      internal: {
        statement: `select links__sync__handlers__deep__client(2310::bigint, 'delete', '{"id":2309}'::jsonb, '{}'::jsonb)`,
        prepared: false,
        error: {
          exec_status: 'FatalError',
          hint: null,
          message: 'Delete not permitted',
          status_code: 'XX000',
          description: null
        },
        arguments: []
      },
      path: '$.args',
      error: 'query execution failed',
      code: 'postgres-error'
    }

      at Object.HasuraApi.defaultErrorHandler [as errorHandler] (../../node_modules/@deep-foundation/hasura/api.tsx:22:45)

  console.log
    error Bad Request {
      internal: {
        statement: `select links__sync__handlers__deep__client(2355::bigint, 'delete', '{"id":2389}'::jsonb, '{}'::jsonb)`,
        prepared: false,
        error: {
          exec_status: 'FatalError',
          hint: null,
          message: 'Delete not permitted',
          status_code: 'XX000',
          description: null
        },
        arguments: []
      },
      path: '$.args',
      error: 'query execution failed',
      code: 'postgres-error'
    }

      at Object.HasuraApi.defaultErrorHandler [as errorHandler] (../../node_modules/@deep-foundation/hasura/api.tsx:22:45)

  console.log
    error Bad Request {
      internal: {
        statement: `select links__sync__handlers__deep__client(2390::bigint, 'delete', '{"id":2471}'::jsonb, '{}'::jsonb)`,
        prepared: false,
        error: {
          exec_status: 'FatalError',
          hint: null,
          message: 'delete [{"id":2471,"from_id":0,"to_id":0,"type_id":23}] rejected because selector_id: 2461 query_id: 2464 user_id: 2390 return false',
          status_code: 'P0001',
          description: null
        },
        arguments: []
      },
      path: '$.args',
      error: 'query execution failed',
      code: 'postgres-error'
    }

      at Object.HasuraApi.defaultErrorHandler [as errorHandler] (../../node_modules/@deep-foundation/hasura/api.tsx:22:45)

  console.log
    error Bad Request {
      internal: {
        statement: `select links__sync__handlers__deep__client(2420::bigint, 'delete', '{"id":2473}'::jsonb, '{}'::jsonb)`,
        prepared: false,
        error: {
          exec_status: 'FatalError',
          hint: null,
          message: 'delete [{"id":2473,"from_id":0,"to_id":0,"type_id":23}] rejected because selector_id: 2461 query_id: 2464 user_id: 2420 return false',
          status_code: 'P0001',
          description: null
        },
        arguments: []
      },
      path: '$.args',
      error: 'query execution failed',
      code: 'postgres-error'
    }

      at Object.HasuraApi.defaultErrorHandler [as errorHandler] (../../node_modules/@deep-foundation/hasura/api.tsx:22:45)

  console.log
    {
      actualErrorMessage: 'DeepClient Delete Error: Success! Handler is called',
      expectedErrorMessage: 'DeepClient Delete Error: Success! Handler is called'
    }

      at log (tests/sync-handlers.ts:2151:21)

  console.log
    updated { data: [ { id: 2583, __typename: 'links' } ] }

      at log (tests/sync-handlers.ts:2183:19)

 FAIL   node  ./integration.test.js (158.599 s)
  client
    ○ skipped deep.linkId guest and login
    ○ skipped name
    ○ skipped { id: 5 }
    ○ skipped { id: { _eq: 5 } }
    ○ skipped { value: 5 }
    ○ skipped { value: 'a' }
    ○ skipped { number: 5 }
    ○ skipped { string: 'a' }
    ○ skipped { number: { value: { _eq: 5 } } }
    ○ skipped { string: { value: { _eq: 'a' } } }
    ○ skipped { object: { value: { _contains: { a: 'b' } } } }
    ○ skipped { from: { value: 5 } }
    ○ skipped { out: { type_id: Contain, value: item, from: where } }
    ○ skipped { value: 5, link: { type_id: 7 } }
    ○ skipped { type: ['@deep-foundation/core', 'Value'] }
    ○ skipped { type: ['@deep-foundation/core', 'Value'] }
    ○ skipped id(packageName,contain)
    ○ skipped { type_id: { _type_of: 25 } }
    ○ skipped { from_id: { _type_of: 25 } }
    ○ skipped { to_id: { _type_of: 25 } }
    ○ skipped { id: { _id: ['@deep-foundation/core', 'Package'] } }
    ○ skipped { type_id: { _id: ['@deep-foundation/core', 'Package'] } }
    ○ skipped { up: { parent_id: { _id: ['@deep-foundation/core', 'Package'] } } }
    ○ skipped idLocal get from minilinks
    ○ skipped insert link with reserved id and string value
    ○ skipped select string table
    ○ skipped deepClient token must not be undefined when secret is passed to apolloClient
    serial
      insert
        ○ skipped one insert
        ○ skipped multiple inserts in one operation
        ○ skipped multiple inserts ine multiple operations
      update
        ○ skipped one update
        ○ skipped multiple updates in one operation
        ○ skipped multiple updates in multiple operations
      delete
        ○ skipped one delete
        ○ skipped multiple deletes in one operation
        ○ skipped multiple deletes in multiple operations
    short value insert
      ○ skipped insert string
      ○ skipped insert number
      ○ skipped insert object
      ○ skipped insert inherited links with values
  join-insert
    ○ skipped { type_id: 1, string: { data: { value: 'abc' } }, from: { data: { type_id: 1 } }, to: { data: { type_id: 1 } } }
  typing
    ○ skipped type required
    ○ skipped particular links
    ○ skipped type 1
    ○ skipped custom id restricted
    ○ skipped link equal from/to type
    ○ skipped link invalid from type
  selectors
    ○ skipped selector include exclude
    criteria
      ○ skipped selector include exclude boolExp
  bool_exp
    value convertation
      ○ skipped insert separately
      ○ skipped insert with link
      ○ skipped update
      ○ skipped delete
      ○ skipped X-Deep-User-Id
      ○ skipped X-Deep-Item-Id
  permissions
    select
      ○ skipped user contain range
      ○ skipped rule select include 1 depth but exclude 2 depth
    insert
      ○ skipped root can insert
      ○ skipped guest cant insert by default
      ○ skipped insert permission can be gived to guest
      ○ skipped insert permission with SelectorFilter
    update
      ○ skipped root can update string value
      ○ skipped guest cant update string value
      ○ skipped update permission can be gived to guest
    delete
      ○ skipped root can delete
      ○ skipped guest cant delete by default
      ○ skipped delete permission can be gived to guest
      ○ skipped delete permission with SelectorFilter
    login
      ○ skipped login permission can be granted
  demo
    ○ skipped user can basic dc operations
  packager
    class
      ○ skipped export import
    sorting
      ○ skipped strict mode: no sorting
      ○ skipped sorting with package, value, and dependencies
      ○ skipped sorting existing package
  tree
    ○ skipped promiseTree
  SerialTransitionsBuilder
    ○ skipped should instantiate correctly
    ○ skipped should append insert transition
    ○ skipped should clear transitions
    ○ skipped should get correct transition type for insert
    ○ skipped should get correct transition type for update
    ○ skipped should get correct transition type for delete
    ○ skipped should execute transition
    ○ skipped should execute transitions
    ○ skipped should execute multiple transitions
    ○ skipped should execute transition and result link be accessible by both alias and index
    ○ skipped should execute transitions and result links be accessible by both alias and index
  sync handlers
    Prepare fuction
      ✓ handleInsert (28 ms)
    DeepClient mini
      ✓ id (21 ms)
      ✓ login as guest and insert (595 ms)
      ✓ login as guest, relogin as admin and insert (998 ms)
      ✓ new client by linkId (398 ms)
      ✓ new client by jwt (308 ms)
      ✓ can (751 ms)
      ✓ objectGet (74 ms)
      ✓ objectSet (62 ms)
      unsafe
        ✓ objectSet (70 ms)
        ✓ objectGet (61 ms)
      select
        ✓ select should return value (74 ms)
        number
          ✓ number: { value: number }} (96 ms)
          ✓ number: { value: { "_in": [ number, number ] }} (103 ms)
          ✓ number: number (87 ms)
          ✓ number: { "_in": [ number, number ]} (241 ms)
        string
          ✓ string: { value: string } (118 ms)
          ✓ string: { value: { "_in": [ string, string ] }} (97 ms)
          ✓ string: 'string' (145 ms)
          ✕ string: { "_in": ['string', 'string'] } (80 ms)
        object
          ✓ object: { value: object } (91 ms)
          ✓ object: { value: { "_in": [ object, object ] }} (90 ms)
          ✓ object: object (92 ms)
          ✓ object: { "_in": [object, object] } (254 ms)
        value
          ✓ value: { value: string } (156 ms)
          ✓ value: string (109 ms)
          ✓ value: { value: object } (115 ms)
          ✓ value: object (110 ms)
          ✓ value: { value: { _in: [ string, number, object ] } }} (115 ms)
          ✓ value: {"_in":[ string, number, object ]} } (179 ms)
      update
        ✓ update string (211 ms)
        ✓ update number (97 ms)
        ✓ update object value (142 ms)
        ✓ update object value by value (81 ms)
      permissions
        select
          ✓ root can select from tree (10705 ms)
          ✓ root can select from can (70 ms)
          ✓ root can select from selectors (16 ms)
          ✓ nobody can select from not permitted tables (29 ms)
          ✓ user contain range (614 ms)
          ✓ rule select include 1 depth but exclude 2 depth (1943 ms)
        insert
          ✓ root can insert (73 ms)
          ✓ guest cant insert by default (312 ms)
          ✓ insert permission can be gived to guest (1484 ms)
          ✓ insert permission with SelectorFilter (6676 ms)
        update
          values
            ✓ root can update value (113 ms)
        delete
          ✓ root can delete (59 ms)
          ✓ nobody can delete from not permitted tables (33 ms)
          ✓ guest cant delete by default (350 ms)
          ✓ delete permission can be gived to guest (1725 ms)
          ✓ delete permission with SelectorFilter (6670 ms)
    require package
      ✓ require mathjs (1697 ms)
      ✓ require jsonschema (350 ms)
    Handle operations
      Handle insert
        ✓ Handle insert on type (253 ms)
        ✓ Handle insert 2 triggers and broke transaction in second (439 ms)
        ✓ Handle insert 1 trigger and 2 types, check not triggered twice (393 ms)
        ✓ Handle insert on type throw error (215 ms)
        ✓ Handle insert on selector (575 ms)
        ✓ Handle insert on type any (365 ms)
        ○ skipped Handle insert on type with sql injection (DAMAGES DATABASE SHOULD BE SKIPPED UNTIL FIXED)
      Handle delete
        ✓ Handle delete on type (263 ms)
        ✓ Handle delete on selector (532 ms)
        ✓ Handle delete on type any (269 ms)
      Handle update
        ✓ Handle update on type (334 ms)
        ✓ Handle update on selector (744 ms)
        ✓ Handle update on type any (223 ms)
      Handle value
        ✓ Handle update on type any (199 ms)
        Handle strings
          ✓ Handle insert string (308 ms)
          ✓ Handle update string (388 ms)
          ✓ Handle delete string (267 ms)
        Handle numbers
          ✓ Handle insert number (313 ms)
          ✓ Handle update number (397 ms)
          ✓ Handle delete number (342 ms)
        Handle objects
          ✓ Handle insert object (344 ms)
          ✓ Handle update object (487 ms)
          ✓ Handle delete object (289 ms)
      Handle IUD for values
        ✓ Handle IUD for strings (599 ms)
        ✓ Handle IUD for numbers (596 ms)
        ✓ Handle IUD for object (552 ms)
      Check data for not bigint
        ✓ Check in delete link (275 ms)
        ✓ Check in update link (694 ms)
  Async handlers
    sync function handle by type with resolve
      ✓ handle insert (1314 ms)
      ✓ handle update when value is inserted (1292 ms)
      ✓ handle update when value is updated (2420 ms)
      ✓ handle update when value is deleted (2416 ms)
      ✓ handle delete (1287 ms)
    sync function handle by type with reject
      ✓ handle insert (1294 ms)
      ✓ handle delete (2313 ms)
    async function handle by type with reject
      ✓ handle insert (1274 ms)
      ✓ handle update (1299 ms)
      ✓ handle delete (1300 ms)
    sync function handle by schedule with resolve
      ✓ handle schedule (17455 ms)
    async function handle by type with resolve using deep client
      ✓ handle insert (1303 ms)
      ✓ handle insert with package jwt (1291 ms)
    handle port
      ✓ handle port (13425 ms)
    handle route
      ✓ handle route (7222 ms)
      ✓ handle route hierarchical insert (9907 ms)
      ✓ handle route hierarchical insert with throw error (14962 ms)
      ✓ handle route gql handler (15071 ms)
    handle by selector
      ✓ handle insert (1871 ms)
      ✓ handle delete (1837 ms)
      ✓ handle update when value is updated (3070 ms)

  ● sync handlers › DeepClient mini › select › string › string: { "_in": ['string', 'string'] }

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      "hellobugfixerstest"
    Received:
      undefined
    
    Message:
      expected undefined to equal 'hellobugfixerstest'

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      600 |           log('selected', selected?.data?.[0]);
      601 |           await deep.delete(id);
    > 602 |           assert.equal(value?.value, 'hellobugfixerstest');
          |                  ^
      603 |         });
      604 |       });
      605 |       describe('object', () => {

      at equal (tests/sync-handlers.ts:602:18)
      at fulfilled (tests/sync-handlers.js:10:24)

Test Suites: 2 failed, 1 skipped, 2 of 3 total
Tests:       1 failed, 105 skipped, 99 passed, 205 total
Snapshots:   0 total
Time:        159.36 s
Ran all test suites matching /index.js|integration.test.js|jest.config.js|react.test.js|unit.test.js/i with tests matching "sync handlers" in 2 projects.
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @deep-foundation/deeplinks@0.0.322 
npm ERR!   at location: /workspace/dev/packages/deeplinks 
```

**Comment by FreePhoenix888** [comment]
This problem interferes https://github.com/deep-foundation/object-to-links-converter development because it uses plv8 handlers
