### ISSUE TITLE
How to set timeout? ApolloError: The operation timed out

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deeplinks#320]
I have approximately `23500` serial operations and want to execute them:
```
  @deep-foundation/russian-laws {
  @deep-foundation/russian-laws   operations: [
  @deep-foundation/russian-laws     { table: 'links', type: 'insert', objects: [Object] },
  @deep-foundation/russian-laws     { table: 'strings', type: 'insert', objects: [Object] },
  @deep-foundation/russian-laws     { table: 'links', type: 'insert', objects: [Object] },
  @deep-foundation/russian-laws     { table: 'links', type: 'insert', objects: [Object] },
  @deep-foundation/russian-laws     { table: 'numbers', type: 'insert', objects: [Object] },
  @deep-foundation/russian-laws     { table: 'links', type: 'insert', objects: [Object] },
  @deep-foundation/russian-laws     ... 23288 more items
  @deep-foundation/russian-laws   ]
  @deep-foundation/russian-laws } +0ms
528 |             catch (e) {
529 |                 const sqlError = (_d = (_c = (_b = (_a = e === null || e === void 0 ? void 0 : e.graphQLErrors) === null || _a === void 0 ? void 0 : _a[0]) === null || _b === void 0 ? void 0 : _b.extensions) === null || _c === void 0 ? void 0 : _c.internal) === null || _d === void 0 ? void 0 : _d.error;
530 |                 if (sqlError === null || sqlError === void 0 ? void 0 : sqlError.message)
531 |                     e.message = sqlError.message;
532 |                 if (!silent)
533 |                     throw new Error(`DeepClient Serial Error: ${e.message}`, { cause: e });
                                ^
error: DeepClient Serial Error: The operation timed out
      at /workspace/dev/russian-laws/node_modules/@deep-foundation/deeplinks/imports/client.js:533:27
      at rejected (/workspace/dev/russian-laws/node_modules/@deep-foundation/deeplinks/imports/client.js:5:47)

21 |     if (err.networkError)
22 |         errors.push(err.networkError);
23 |     return (errors
24 |         .map(function (err) {
25 |         return (utilities.isNonNullObject(err) && err.message) || "Error message not found.";
26 |     })
                                                                                                                               ^
ApolloError: The operation timed out
      at new ApolloError (/workspace/dev/russian-laws/node_modules/@apollo/client/errors/errors.cjs:26:123)
      at error (/workspace/dev/russian-laws/node_modules/@apollo/client/core/core.cjs:1474:102)
      at notifySubscription (/workspace/dev/russian-laws/node_modules/zen-observable/lib/Observable.js:140:18)
      at onNotify (/workspace/dev/russian-laws/node_modules/zen-observable/lib/Observable.js:179:3)
      at error (/workspace/dev/russian-laws/node_modules/zen-observable/lib/Observable.js:240:7)
      at /workspace/dev/russian-laws/node_modules/@apollo/client/utilities/utilities.cjs:1274:30
      at notifySubscription (/workspace/dev/russian-laws/node_modules/zen-observable/lib/Observable.js:140:18)
      at onNotify (/workspace/dev/russian-laws/node_modules/zen-observable/lib/Observable.js:179:3)
      at error (/workspace/dev/russian-laws/node_modules/zen-observable/lib/Observable.js:240:7)
      at /workspace/dev/russian-laws/node_modules/@apollo/client/utilities/utilities.cjs:1253:61
✗ import and export [837953.41ms]

 0 pass
 1 fail
Ran 1 tests across 1 files. [840.11s]
```

But I get `ApolloError: The operation timed out`. Is there a way to change timeout time? If not we should add this feature

**Comment by FreePhoenix888** [comment]
https://hasura.io/learn/graphql/hasura-advanced/security/6-timeouts/

**Comment by FreePhoenix888** [comment]
Workaround is to chunk your operations
