### ISSUE TITLE
Error: Id not found by [["@deep-foundation/deepcase"]]

### ISSUE THREAD

**Issue by Konard** [deep-foundation/deeplinks#334]
```
5m 45s
Run npm run migrate
> @deep-foundation/deeplinks@0.0.339 migrate
> npm run package:build && npx migrate@latest up --matches '*.js'
> @deep-foundation/deeplinks@0.0.339 package:build
> tsc --project tsconfig.json
ok
ok
(node:4813) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  up : 1616701513782-links.js
  up : 1616701513790-selectors-cache.js
  up : 1621815803560-auto-indexes.js
  up : 1621815803572-materialized-path.js
  up : 1621815803592-type-mp.js
  up : 1622230000000-reserved-links.js
  up : 1622421760250-values.js
  up : 1622421760256-types.js
admin 380
  up : 1622421760258-selectors.js
  up : 1622421760259-can.js
  up : 1622421760260-permissions.js
  up : 1623023831753-jwt.js
  up : 1637975150573-packager.js
  up : 1637975150590-promises.js
  up : 1642827746040-demo.js
  up : 1655979260869-sync-handlers.js
  up : 1657486935281-authorization.js
  up : 1657720948151-handlers.js
  up : 1658622099992-unvalue.js
  up : 1658909585601-hasura-storage.js
  up : 1661392616544-core-symbols.js
  up : 1664940577200-tsx.js
  up : 1664940577209-deepcase.js
  up : 1677340638677-npm-packager.js
  up : 1678940577209-deepcase.js
  error : Error: Id not found by [["@deep-foundation/deepcase"]]
Error: Id not found by [["@deep-foundation/deepcase"]]
    at DeepClient.<anonymous> (file:///home/runner/work/deeplinks/deeplinks/imports/client.js:799:23)
    at Generator.next (<anonymous>)
    at fulfilled (file:///home/runner/work/deeplinks/deeplinks/imports/client.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Process completed with exit code 1.
```

This error occurs because installation of `@deep-foundation/deepcase` fails.
One of the reason might be, that someone didn't use `npm run npm-release` command when new release of `deepcase` was published, meaning that `deep.json` is not synchronized with `package.json`, that gives error on installation of `@deep-foundation/deepcase`.

**Comment by Konard** [comment]
Regression is detected at https://github.com/deep-foundation/deepcase/commit/0d24e965fd1592c29981baa778182478de7d4f9f

**Comment by Konard** [comment]
Attempted to fix the regression using `npm run package:release` ([source](https://github.com/deep-foundation/deepcase?tab=readme-ov-file#release-a-new-version))at https://github.com/deep-foundation/deepcase/commit/8223dd46c7dc351f75550981453b6f7b6727c17b commit.

**Comment by Konard** [comment]
Fixed at https://github.com/deep-foundation/dev/commit/d3ab08badb419d4f6da3b85644cbdaa78120ccb4
