### ISSUE TITLE
jest encountered an unexpected token SyntaxError: Cannot use import statement outside a module typescript

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deeplinks#87]
# How to reproduce

Run `npm test` or `npm run test` or `jest`

**Comment by FreePhoenix888** [comment]
How I have fixed it in my a little project that is created to find how to fix this:
```bash
freephoenix888@freephoenix888:~/Programming/test$ npm run test

> test@1.0.0 test
> jest

 FAIL  ./sum.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/freephoenix888/Programming/test/sum.test.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { sum } from "./sum";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1449:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.379 s
Ran all test suites.
freephoenix888@freephoenix888:~/Programming/test$ npx ts-jest config:init

Jest configuration written to "/home/freephoenix888/Programming/test/jest.config.js".
freephoenix888@freephoenix888:~/Programming/test$ npx jest
ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 PASS  ./sum.test.ts
  ✓ sum (2 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.118 s
Ran all test suites.
```

**Comment by FreePhoenix888** [comment]
I have done the same actions as in answer from stackoverflow quoted above and it does not fix our error:

```
freephoenix888@freephoenix888:~/Programming/dev/packages/deeplinks$ npx jest
 FAIL  ./main.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/freephoenix888/Programming/dev/packages/deeplinks/node_modules/@deep-foundation/store/local.tsx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import React, { Context, ReactNode, useState, createContext, useEffect, useMemo, useRef } from 'react';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import { ApolloClient, ApolloError, ApolloQueryResult, useApolloClient, gql, useQuery, useSubscription } from "@apollo/client";
      3 | import { generateApolloClient, IApolloClient } from "@deep-foundation/hasura/client";
    > 4 | import { useLocalStore } from "@deep-foundation/store/local";
        | ^
      5 | import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
      6 | import { deprecate, inherits } from "util";
      7 | import { deleteMutation, generateQuery, generateQueryData, generateSerial, insertMutation, updateMutation } from "./gql";

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1449:14)
      at Object.<anonymous> (imports/client.tsx:4:1)
      at Object.<anonymous> (tests/client.ts:2:1)
      at Object.<anonymous> (main.test.ts:5:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        8.686 s
Ran all test suites.
```


All dev dependencies are the same as that project:
```
  "devDependencies": {
    "@types/jest": "^29.2.4",
    "jest": "^29.3.1",
    "ts-jest": "^29.0.3",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4"
  }
```

**Comment by FreePhoenix888** [comment]
As we can see this error shows error not for code of this package (deeplinks), it shows the line from one of the dependencies - @deep-foundation/store

And this error related to the file with `tsx` extension

**Comment by FreePhoenix888** [comment]
`ts-jest` documentation tells us that `ts/tsx` files will be transformed to `CommonJS` files if we have `ts-jest` preset in the `jest.config.ts`
[ts-jest presets](https://kulshekhar.github.io/ts-jest/docs/getting-started/presets/)

I use that preset in `jest.config.ts` already:
```typescript
/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
};
```

Is the problem cause is `store` package? 🤔

**Comment by FreePhoenix888** [comment]
I have found out that in the previous npm releases we were building our `tsx?` files to js files. I have added build before publishing and now everything is working
