### ISSUE TITLE
field "type_id" not found in type: 'strings'

### ISSUE THREAD

**Issue by Konard** [deep-foundation/deeplinks#99]
```ts
import { generateApolloClient } from '@deep-foundation/hasura/client';
import { DeepClient } from '@deep-foundation/deeplinks/imports/client';
import config from './config.json';

const gql = generateApolloClient(config.endpoint);
const deep = new DeepClient({ apolloClient: gql });

const run = async () => {
  const result = await deep.select(
    { link_id: { _eq: 837 } },
    {
      table: 'strings',
      // returning: 'id'
    }
  );
  console.log(result);
}
run();
```
This code gives an error:
```
gitpod /workspace/npm-packager (main) $ npm run test-deep

> @deep-foundation/npm-packager@0.0.2 test-deep
> npx ts-node test-deep.ts

/workspace/npm-packager/node_modules/@apollo/client/errors/index.js:29
        var _this = _super.call(this, errorMessage) || this;
                           ^
ApolloError: field "type_id" not found in type: 'strings'
    at new ApolloError (/workspace/npm-packager/node_modules/@apollo/client/errors/index.js:29:28)
    at /workspace/npm-packager/node_modules/@apollo/client/core/QueryManager.js:634:47
    at both (/workspace/npm-packager/node_modules/@apollo/client/utilities/observables/asyncMap.js:16:53)
    at /workspace/npm-packager/node_modules/@apollo/client/utilities/observables/asyncMap.js:9:72
    at new Promise (<anonymous>)
    at Object.then (/workspace/npm-packager/node_modules/@apollo/client/utilities/observables/asyncMap.js:9:24)
    at Object.next (/workspace/npm-packager/node_modules/@apollo/client/utilities/observables/asyncMap.js:17:49)
    at notifySubscription (/workspace/npm-packager/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/workspace/npm-packager/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/workspace/npm-packager/node_modules/zen-observable/lib/Observable.js:235:7) {
  graphQLErrors: [
    {
      extensions: [Object],
      message: `field "type_id" not found in type: 'strings'`
    }
  ],
  clientErrors: [],
  networkError: null,
  extraInfo: undefined
}
```
The workaround is to add `returning` by uncommenting `// returning: 'id'` line.
But why it is required to do so?

**Comment by FreePhoenix888** [comment]
```
await deep.select(
    {
        link_id: {_eq : 1388}
    },
    {
        "table": "numbers",
    }
)
```
![image](https://user-images.githubusercontent.com/66206278/216905768-b88db14b-b0d3-4f8b-a2ab-42f2f8b09050.png)
The same problem

**Comment by FreePhoenix888** [comment]
```ts
await deep.select(
    {
        link: {
            id: { _eq : 1388 }
        }
    },
    {
        "table": "numbers",
    }
)
```
Does not work too

**Comment by Konard** [comment]
5000 ₽ can be claimed as a reward for this bug.
